### ISSUE TITLE
help to attach Crimea to Ukraine

### ISSUE THREAD

**Issue by espinielli** [Fil/visionscarto-world-atlas#7]
Hi @Fil ,
I am looking for some magic incantation using command line cartography in order to produce my own version of world atlas (a fork of yours ;-) where I could attach Crimea to Ukraine rather than Russia.

I read your `run` script in this repo in the hope to see whether something like that was already there...but no luck

Any helps is welcome
Super thanks
PS: I am also curious to learn about the process, tools, steps you use to implement your fixes as per `run` script...

**Comment by Fil** [comment]
Ah! I have a version that does this, and cleans quite a lot of other things that I didn't like in the original shapes. I still have to take a moment to clean it up and release it to the public. One of my goals for ~~november~~ january 23. I can send you some information privately in the meantime.

**Comment by espinielli** [comment]
That would be great! Thanks!
